# Generated by Django 5.2.3 on 2025-06-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_acc', '0002_customuser_profile_picture_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
