# Generated by Django 5.2.3 on 2025-06-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_acc', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
