# Generated by Django 5.2.3 on 2025-06-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_acc', '0005_rename_profile_picture_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/profiles/default-user.png', null=True, upload_to='media/profiles'),
        ),
    ]
