# Generated by Django 5.2.3 on 2025-06-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_acc', '0007_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-user.png', null=True, upload_to='media/'),
        ),
    ]
